image: docker.io/qazando/appium-maven

stages:
  - test

test-job:
  stage: test
  script:
    - mvn test -Dcucumber.filter.tags="@Regressive" -Dplatform=device_farm -Duser=dernivalliandro_HC5zlF -Dkey=sNwiuaTaDB2TbfPcVzi1